# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EstimapRecreation
                                 A QGIS plugin
 Ecosystem services mapping at
European scale (ESTIMAP)- Recreation
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-02-08
        copyright            : (C) 2019 by Natcapes
        email                : nik@nikosalexandris.net
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Natcapes'
__date__ = '2019-02-08'
__copyright__ = '(C) 2019 by Natcapes'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load EstimapRecreation class from file EstimapRecreation.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .estimap_recreation import EstimapRecreationPlugin
    return EstimapRecreationPlugin()
