# -*- coding: utf-8 -*-

"""
/***************************************************************************
 EstimapRecreation
                                 A QGIS plugin
 Ecosystem services mapping at
European scale (ESTIMAP)- Recreation
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-02-08
        copyright            : (C) 2019 by Natcapes
        email                : nik@nikosalexandris.net
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Natcapes'
__date__ = '2019-02-08'
__copyright__ = '(C) 2019 by Natcapes'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect

from qgis.core import QgsProcessingAlgorithm, QgsApplication
from estimap_recreation.estimap_recreation_provider import EstimapRecreationProvider

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class EstimapRecreationPlugin(object):

    def __init__(self):
        self.provider = EstimapRecreationProvider()

    def initGui(self):
        QgsApplication.processingRegistry().addProvider(self.provider)

    def unload(self):
        QgsApplication.processingRegistry().removeProvider(self.provider)
